sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T25v2iCbBoFqYMob4sIqEFVqG4RsbkB1Dyp/0LIH3VPrV5g1ZJhwwQsHQAT6um6U3zF9y0Z3LP+ANgYsnXIo/e2Uh+DEykVB+UXi9LJ6ghpdu/1kX76s/ABIesJLuOdZbFfOcMQ90xJgIhd1/WmBBS1JASJYzK+fNMoiNAcsLpD5WQX83bjAUJ8D8xCoA/DtMNTjeo3U5HUL7juwITmAkjxQK/QPYJJrAYVRQTmzKTrmj1h35B+6fUfLpfrMvFHcEcghSi/jhSMCFantszLLXyBhG6PU/dM2czdMlhS7s1i6plBrpFC1ESXMnqtW76BF0c+ZTyUGETSY+3OZYHCr9xJMYeLbjyh4udmN5IeRIFCtPaD7TF0Zhy4jcPtLWCW9VJ+TEVAf9F3vQtEhS7pGXT5q8COOiL1RphdiWvA4i6l6yn0XbHhEPXTGNccSM8ZNel/dCe6v7eX2odByN523j+rPrFl6pBLQjxOnpbfHhqJtZL5VgNKaLX+TiiJeaVm4uhlvSi2b/wc8RL4KleKsVX8vy3REoCvIrZq1adbsNnYlULFs3dfeA3k/A04xffk/pZdo/O+2j3MmyxrXVVKJl3g+xXlR6NUg0rUAKtw+QSdccUxAjH0Y75zSEywXEyxTfHwGvnDnyW5eX/9HyIcJdyvy9VUsHFIOMKs6mu0XLHo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Locrine-Mucedorus_1548
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy